---
title: "SuppFig6A_Heatmap"
output: html_document
date: "2026-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(pheatmap)

# Load object
lungquery <- readRDS("C:/Users/sshaikh9/Downloads/lungQuery_After_AZ_Normalized.rds")
DefaultAssay(lungquery) <- "RNA"

# Output folder
out_dir <- "C:/Users/sshaikh9/Documents/Signaling_Heatmap_Output"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# Gene list
custom_feature_list <- c(
  "ISG15","F3","IGSF3","S100A11","RAB13","IFI16","PRAF1","CREG1",
  "RHOA","RHOB","CYP1B1","STAT1","FN1","IGFBP2","IGFBP5","FILIP1L",
  "IGFBP7","EGR1","CXCL14","SPARC","GLT8D2","TFAP2A","RGL2",
  "CDKN1A","CCN2","THBS1","NES","CITED2","RAC1","IGFBP1","IGFBP3",
  "COL1A2","SERPINE1","TES","IRF5","TP53","TSPYL5","CDKN2A",
  "CDKN2B","AQP1","GSN","OPTN","VIM","IRF7","CDKN1C","SMPD1",
  "HPS5","HTATIP2","CCN1","CCND1","MMP1","CRYAB","IGFBP6",
  "FABP5","MDM2","ING1","RABGGTB","HSPA2","TNFAIP2","NDN",
  "THBS3","ALDH1A3","TGFB1I1","RBL1","MAP1LC3B","MAP2K3",
  "IGFBP4","NME2","SMURF2","RAB31","SERPINB2","CRY2","RRAS2",
  "EIF2S2","SOD1"
)

custom_feature_list <- unique(custom_feature_list)
custom_feature_list <- intersect(custom_feature_list, rownames(lungquery))

# Average expression by donor group and lineage
celltype_mean <- AverageExpression(
  object = lungquery,
  group.by = c("Donor_Group", "predicted.ann_level_1"),
  assays = "RNA",
  features = custom_feature_list,
  slot = "data"
)

mat <- as.matrix(celltype_mean$RNA)

# Column order: Epithelial first, then Stroma
donor_order <- c(
  "PT-NEWBORN", "FT-NEWBORN", "INFANT", "Children",
  "Adolescent", "Young-Adult", "Aged-or-Diseased", "PT-BPD"
)

lineage_order <- c("Epithelial", "Stroma")

ordered_cols <- c()

for (lin in lineage_order) {
  for (don in donor_order) {
    col_name <- paste(don, lin, sep = "-")
    if (col_name %in% colnames(mat)) {
      ordered_cols <- c(ordered_cols, col_name)
    }
  }
}

mat2 <- mat[custom_feature_list, ordered_cols, drop = FALSE]

# Row-wise Z-score
mat_scaled2 <- t(scale(t(mat2)))
mat_scaled2[is.na(mat_scaled2)] <- 0
mat_scaled2[mat_scaled2 > 4] <- 4
mat_scaled2[mat_scaled2 < -2] <- -2

# Annotation
annotation_col <- data.frame(
  Lineage = sub("^.*-", "", colnames(mat_scaled2))
)

rownames(annotation_col) <- colnames(mat_scaled2)

ann_colors <- list(
  Lineage = c(
    Epithelial = "#F28E8B",
    Stroma = "#C77CFF"
  )
)

# Column labels
display_labels <- colnames(mat_scaled2)
display_labels <- gsub("-Epithelial", "", display_labels)
display_labels <- gsub("-Stroma", "", display_labels)

# Save CSVs
write.csv(
  mat2,
  file.path(out_dir, "Epithelial_Stroma_AverageExpression.csv"),
  quote = FALSE
)

write.csv(
  mat_scaled2,
  file.path(out_dir, "Epithelial_Stroma_Zscore_PlottedMatrix.csv"),
  quote = FALSE
)

# Save heatmap
png_file <- file.path(out_dir, "Epithelial_Stroma_SenescenceStress_heatmap.png")

png(png_file, width = 7000, height = 5000, res = 300)

pheatmap(
  mat_scaled2,
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  labels_col = display_labels,
  gaps_col = 8,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  border_color = "black",
  scale = "none",
  color = colorRampPalette(c("#2166AC", "white", "#FDD16A", "#B2182B"))(100),
  breaks = seq(-2, 4, length.out = 101),
  fontsize_row = 5,
  fontsize_col = 7,
  angle_col = 90,
  main = ""
)

dev.off()

# Show plot in RStudio
graphics.off()

pheatmap(
  mat_scaled2,
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  labels_col = display_labels,
  gaps_col = 8,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  border_color = "black",
  scale = "none",
  color = colorRampPalette(c("#2166AC", "white", "#FDD16A", "#B2182B"))(100),
  breaks = seq(-2, 4, length.out = 101),
  fontsize_row = 5,
  fontsize_col = 7,
  angle_col = 90,
  main = ""
)
```

```{r}
# Average expression values
write.csv(
  mat2,
  "Epithelial_Stroma_AverageExpression.csv",
  quote = FALSE
)

# Z-score matrix actually plotted in heatmap
write.csv(
  mat_scaled2,
  "Epithelial_Stroma_Zscore_PlottedMatrix.csv",
  quote = FALSE
)
```

