---
title: "Lineage Heatmap"
output: html_document
date: "2026-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(pheatmap)

# Load object
lungquery <- readRDS("C:/Users/sshaikh9/Downloads/lungQuery_After_AZ_Normalized.rds")
DefaultAssay(lungquery) <- "RNA"

# Output folder
out_dir <- "C:/Users/sshaikh9/Documents/Signaling_Heatmap_Output"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# Gene list
custom_feature_list <- c(
  "DNMT3A",
  "HSPA1A",
  "MYCT1",
  "KLF4",
  "KMT2A",
  "NANOG",
  "KRT7",
  "KRT8",
  "MYCBP2",
  "KDM6B",
  "KRT15",
  "DNMT1",
  "PCNA"
)

custom_feature_list <- unique(custom_feature_list)
custom_feature_list <- intersect(custom_feature_list, rownames(lungquery))

# Average expression by donor group and lineage
celltype_mean <- AverageExpression(
  object = lungquery,
  group.by = c("Donor_Group", "predicted.ann_level_1"),
  assays = "RNA",
  features = custom_feature_list,
  slot = "data"
)

mat <- as.matrix(celltype_mean$RNA)

# Column order: Epithelial first, then Stroma
donor_order <- c(
  "PT-NEWBORN", "FT-NEWBORN", "INFANT", "Children",
  "Adolescent", "Young-Adult", "Aged-or-Diseased", "PT-BPD"
)

lineage_order <- c("Epithelial", "Stroma")

ordered_cols <- c()

for (lin in lineage_order) {
  for (don in donor_order) {
    col_name <- paste(don, lin, sep = "-")
    if (col_name %in% colnames(mat)) {
      ordered_cols <- c(ordered_cols, col_name)
    }
  }
}

mat2 <- mat[custom_feature_list, ordered_cols, drop = FALSE]

# Row-wise Z-score
mat_scaled2 <- t(scale(t(mat2)))
mat_scaled2[is.na(mat_scaled2)] <- 0
mat_scaled2[mat_scaled2 > 4] <- 4
mat_scaled2[mat_scaled2 < -2] <- -2

# Annotation
annotation_col <- data.frame(
  Lineage = sub("^.*-", "", colnames(mat_scaled2))
)

rownames(annotation_col) <- colnames(mat_scaled2)

ann_colors <- list(
  Lineage = c(
    Epithelial = "#F28E8B",
    Stroma = "#C77CFF"
  )
)

# Column labels
display_labels <- colnames(mat_scaled2)
display_labels <- gsub("-Epithelial", "", display_labels)
display_labels <- gsub("-Stroma", "", display_labels)

# Save CSVs
write.csv(
  mat2,
  file.path(out_dir, "Epithelial_Stroma_AverageExpression.csv"),
  quote = FALSE
)

write.csv(
  mat_scaled2,
  file.path(out_dir, "Epithelial_Stroma_Zscore_PlottedMatrix.csv"),
  quote = FALSE
)

# Save heatmap
png_file <- file.path(out_dir, "Epithelial_Stroma_SenescenceStress_heatmap.png")

png(png_file, width = 7000, height = 5000, res = 300)

pheatmap(
  mat_scaled2,
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  labels_col = display_labels,
  gaps_col = 8,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  border_color = "black",
  scale = "none",
  color = colorRampPalette(c("#2166AC", "white", "#FDD16A", "#B2182B"))(100),
  breaks = seq(-2, 4, length.out = 101),
  fontsize_row = 5,
  fontsize_col = 7,
  angle_col = 90,
  main = ""
)

dev.off()

# Show plot in RStudio
graphics.off()

pheatmap(
  mat_scaled2,
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  labels_col = display_labels,
  gaps_col = 8,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  border_color = "black",
  scale = "none",
  color = colorRampPalette(c("#2166AC", "white", "#FDD16A", "#B2182B"))(100),
  breaks = seq(-2, 4, length.out = 101),
  fontsize_row = 5,
  fontsize_col = 7,
  angle_col = 90,
  main = ""
)
```

```{r}
# Average expression values
write.csv(
  mat2,
  "Epithelial_Stroma_AverageExpression.csv",
  quote = FALSE
)

# Z-score matrix actually plotted in heatmap
write.csv(
  mat_scaled2,
  "Epithelial_Stroma_Zscore_PlottedMatrix.csv",
  quote = FALSE
)
```

```{r}
DimPlot(
  epi_dev,
  reduction = "umap",
  group.by = "Stage"
) +
  ggtitle("Saccular versus alveolar epithelial cells")
```

```{r}
DimPlot(
  epi_dev,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE
)
```
```{r}
epi_dev$Stage <- factor(
  epi_dev$Stage,
  levels = c("Saccular", "Alveolar")
)
```
```{r}
DimPlot(
  epi_dev,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE
)
```
```{r}
epi_dev$predicted.ann_finest_level <- factor(
  epi_dev$predicted.ann_finest_level,
  levels = c("AT2", "AT2 proliferating", "AT1")
)
```

```{r}
cds_saccular <- cds[, colData(cds)$Stage == "Saccular"]

plot_cells(
  cds_saccular,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Saccular epithelial pseudotime") +
  theme_classic(base_size = 14)
```

```{r}
epi_saccular <- subset(
  epi_dev,
  subset = Stage == "Saccular"
)
```

```{r}
cds_saccular <- as.cell_data_set(epi_saccular)

rowData(cds_saccular)$gene_name <- rownames(cds_saccular)
rowData(cds_saccular)$gene_short_name <- rownames(cds_saccular)

cds_saccular@int_colData@listData$reducedDims$UMAP <-
  epi_saccular@reductions$umap@cell.embeddings
```

```{r}
cds_saccular <- cluster_cells(
  cds_saccular,
  reduction_method = "UMAP"
)
```

```{r}
recreate.partition <- c(rep(1, ncol(cds_saccular)))
names(recreate.partition) <- colnames(cds_saccular)

cds_saccular@clusters$UMAP$partitions <-
  as.factor(recreate.partition)
```

```{r}
cds_saccular <- learn_graph(
  cds_saccular,
  use_partition = FALSE
)
```

```{r}
root_node <- get_root_AT2(cds_saccular)

cds_saccular <- order_cells(
  cds_saccular,
  root_pr_nodes = root_node
)
```

```{r}
DimPlot(
  epi_dev,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE
)
```

```{r}
epi_alveolar <- subset(
  epi_dev,
  subset = Stage == "Alveolar"
)

cds_alveolar <- as.cell_data_set(epi_alveolar)

rowData(cds_alveolar)$gene_name <- rownames(cds_alveolar)
rowData(cds_alveolar)$gene_short_name <- rownames(cds_alveolar)

cds_alveolar@int_colData@listData$reducedDims$UMAP <-
  epi_alveolar@reductions$umap@cell.embeddings

cds_alveolar <- cluster_cells(cds_alveolar, reduction_method = "UMAP")

recreate.partition <- c(rep(1, ncol(cds_alveolar)))
names(recreate.partition) <- colnames(cds_alveolar)
cds_alveolar@clusters$UMAP$partitions <- as.factor(recreate.partition)

cds_alveolar <- learn_graph(
  cds_alveolar,
  use_partition = FALSE,
  close_loop = FALSE
)

root_node_alveolar <- get_root_AT2(cds_alveolar, root_cell_type = "AT2")

cds_alveolar <- order_cells(
  cds_alveolar,
  reduction_method = "UMAP",
  root_pr_nodes = root_node_alveolar
)

colData(cds_alveolar)$monocle3_pseudotime <- pseudotime(cds_alveolar)

p_alveolar <- plot_cells(
  cds_alveolar,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Alveolar epithelial pseudotime") +
  theme_classic(base_size = 14)

p_alveolar
```

```{r}
epi_saccular <- subset(
  epi_dev,
  subset = Stage == "Saccular"
)

cds_saccular <- as.cell_data_set(epi_saccular)

rowData(cds_saccular)$gene_name <- rownames(cds_saccular)
rowData(cds_saccular)$gene_short_name <- rownames(cds_saccular)

cds_saccular@int_colData@listData$reducedDims$UMAP <-
  epi_saccular@reductions$umap@cell.embeddings

cds_saccular <- cluster_cells(
  cds_saccular,
  reduction_method = "UMAP"
)

recreate.partition <- c(rep(1, ncol(cds_saccular)))
names(recreate.partition) <- colnames(cds_saccular)

cds_saccular@clusters$UMAP$partitions <-
  as.factor(recreate.partition)

cds_saccular <- learn_graph(
  cds_saccular,
  use_partition = FALSE,
  close_loop = FALSE
)

root_node_saccular <- get_root_AT2(
  cds_saccular,
  root_cell_type = "AT2"
)

cds_saccular <- order_cells(
  cds_saccular,
  reduction_method = "UMAP",
  root_pr_nodes = root_node_saccular
)

colData(cds_saccular)$monocle3_pseudotime <- pseudotime(cds_saccular)

p_saccular <- plot_cells(
  cds_saccular,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Saccular epithelial pseudotime") +
  theme_classic(base_size = 14)

p_saccular
```

```{r}
ggsave(file.path(outdir, "Saccular_Epithelial_Pseudotime.png"),
       p_saccular, width = 7, height = 6, dpi = 300, bg = "white")

ggsave(file.path(outdir, "Alveolar_Epithelial_Pseudotime.png"),
       p_alveolar, width = 7, height = 6, dpi = 300, bg = "white")
```

```{r}
pseudo_df <- as.data.frame(colData(cds))

pseudo_df <- pseudo_df %>%
  filter(is.finite(monocle3_pseudotime))

pseudo_df$Stage <- factor(
  pseudo_df$Stage,
  levels = c("Saccular", "Alveolar")
)

p_box_stage <- ggplot(
  pseudo_df,
  aes(
    x = Stage,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    width = 0.7,
    alpha = 0.8,
    outlier.size = 0.3
  ) +
  geom_jitter(
    width = 0.15,
    alpha = 0.15,
    size = 0.2
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Pseudotime distribution by developmental stage"
  ) +
  theme(
    legend.position = "none"
  )

p_box_stage
```

```{r}
ggsave(
  "Pseudotime_Boxplot_Saccular_vs_Alveolar.png",
  p_box_stage,
  width = 5,
  height = 5,
  dpi = 300,
  bg = "white"
)
```

```{r}
p_box_subtype <- ggplot(
  pseudo_df,
  aes(
    x = predicted.ann_finest_level,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    position = position_dodge(0.8),
    outlier.size = 0.3
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Pseudotime distribution across epithelial states"
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

p_box_subtype
```

```{r}
ggsave(
  "Pseudotime_Boxplot_Epithelial_Subtypes.png",
  p_box_subtype,
  width = 7,
  height = 5,
  dpi = 300,
  bg = "white"
)
```

```{r}
genes_heatmap <- c(
  # AT2
  "SFTPC","SFTPB","SFTPA1","SFTPA2",

  # Transitional
  "KRT8","KRT18","KRT19","CLDN4","AXL",

  # AT1
  "AGER","PDPN","HOPX","CAV1",

  # Senescence
  "CDKN1A","GLB1","GDF15",

  # Inflammatory
  "IL6ST","IL1B",

  # Repair/plasticity
  "MYC","TGFB1","BMPR2"
)

genes_heatmap <- genes_heatmap[
  genes_heatmap %in% rownames(cds)
]

genes_heatmap
```

```{r}
pseudo <- pseudotime(cds)

valid_cells <- names(pseudo)[
  is.finite(pseudo) & !is.na(pseudo)
]

valid_cells <- valid_cells[
  order(pseudo[valid_cells])
]
```

```{r}
expr_mat <- exprs(cds)[
  genes_heatmap,
  valid_cells
]

expr_mat <- as.matrix(expr_mat)
```

```{r}
n_bins <- 50

pseudo_valid <- pseudo[valid_cells]

bins <- cut(
  pseudo_valid,
  breaks = n_bins,
  labels = FALSE
)

bin_expr <- sapply(
  sort(unique(bins)),
  function(b){
    rowMeans(
      expr_mat[, bins == b, drop = FALSE]
    )
  }
)

colnames(bin_expr) <- paste0(
  "Bin_",
  seq_len(ncol(bin_expr))
)
```

```{r}
bin_expr_scaled <- t(
  scale(
    t(bin_expr)
  )
)

bin_expr_scaled <- t(
  scale(
    t(bin_expr)
  )
) 
bin_expr_scaled[bin_expr_scaled > 2] <- 2
bin_expr_scaled[bin_expr_scaled < -2] <- -2
```

```{r}
dim(bin_expr_scaled)
rownames(bin_expr_scaled)
```

```{r}
heatmap_plot <- pheatmap(
  bin_expr_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  show_colnames = FALSE,
  fontsize_row = 10,
  border_color = NA,
  breaks = seq(-2, 2, length.out = 100),
  main = "Gene dynamics across epithelial pseudotime"
)

heatmap_plot
```

```{r}
write.csv(
  bin_expr_scaled,
  "Epithelial_Pseudotime_Heatmap_Zscore_Matrix.csv",
  quote = FALSE
)
```

```{r}
ls()
```

```{r}
gene_order <- c(
  "SFTPA1","SFTPA2","SFTPB","SFTPC",
  "KRT8","KRT18","KRT19","CLDN4","AXL",
  "AGER","PDPN","HOPX","CAV1",
  "CDKN1A","GLB1","GDF15",
  "IL6ST","IL1B",
  "MYC","TGFB1","BMPR2"
)

gene_order <- gene_order[
  gene_order %in% rownames(bin_expr_scaled)
]

mat_ordered <- bin_expr_scaled[
  gene_order,
  ,
  drop = FALSE
]

dim(mat_ordered)
```

```{r}
gene_order <- c(
  # AT2
  "SFTPA1","SFTPA2","SFTPB","SFTPC",

  # Transitional
  "KRT8","KRT18","KRT19","CLDN4","AXL",

  # AT1
  "AGER","PDPN","HOPX","CAV1",

  # Senescence
  "CDKN1A","GLB1","GDF15",

  # Inflammatory
  "IL6ST","IL1B",

  # Repair/plasticity
  "MYC","TGFB1","BMPR2"
)

gene_order <- gene_order[
  gene_order %in% rownames(bin_expr_scaled)
]

mat_ordered <- bin_expr_scaled[
  gene_order,
]
```

```{r}
pheatmap(
  mat_ordered,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  show_colnames = FALSE,
  fontsize_row = 11,
  border_color = NA,
  breaks = seq(-2, 2, length.out = 100),
  main = "AT2-to-AT1 epithelial maturation across pseudotime"
)
```

```{r}
library(pheatmap)

pheatmap(
  mat_ordered,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  show_colnames = FALSE,
  fontsize_row = 10,
  border_color = NA,
  main = "AT2-to-AT1 epithelial maturation across pseudotime"
)
```

```{r}
gene_group <- data.frame(
  Gene_Group = c(
    rep("AT2 markers", 4),
    rep("Transitional markers", 5),
    rep("AT1 markers", 4),
    rep("Senescence markers", 3),
    rep("Inflammatory markers", 2),
    rep("Repair/plasticity markers", 3)
  )
)

rownames(gene_group) <- rownames(mat_ordered)

pheatmap(
  mat_ordered,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  annotation_row = gene_group,
  gaps_row = gaps_row,
  show_colnames = FALSE,
  fontsize_row = 10,
  border_color = NA,
  breaks = seq(-2, 2, length.out = 100),
  main = "AT2-to-AT1 epithelial maturation across pseudotime"
)
```

```{r}
write.csv(
  mat_ordered,
  file = "AT2_AT1_Pseudotime_Heatmap_Zscore_Matrix.csv",
  quote = FALSE
)
```

```{r}
write.csv(
  mat_ordered,
  file = file.path(
    outdir,
    "AT2_AT1_Pseudotime_Heatmap_Zscore_Matrix.csv"
  ),
  quote = FALSE
)
```

```{r}
gene_annotation <- data.frame(
  Gene = rownames(mat_ordered),
  Gene_Group = gene_group$Gene_Group
)

write.csv(
  gene_annotation,
  file = file.path(
    outdir,
    "AT2_AT1_Pseudotime_Gene_Annotations.csv"
  ),
  row.names = FALSE,
  quote = FALSE
)
```

```{r}
write.csv(
  bin_expr,
  file = file.path(
    outdir,
    "AT2_AT1_Pseudotime_AverageExpression.csv"
  ),
  quote = FALSE
)
```

```{r}
Idents(fibro_sa) <- "predicted.ann_finest_level"

cds_fibro_sa <- as.cell_data_set(fibro_sa)

rowData(cds_fibro_sa)$gene_name <- rownames(cds_fibro_sa)
rowData(cds_fibro_sa)$gene_short_name <- rownames(cds_fibro_sa)

cds_fibro_sa@int_colData@listData$reducedDims$UMAP <-
  fibro_sa@reductions$umap@cell.embeddings

cds_fibro_sa <- cluster_cells(
  cds_fibro_sa,
  reduction_method = "UMAP"
)

recreate.partition <- c(rep(1, ncol(cds_fibro_sa)))
names(recreate.partition) <- colnames(cds_fibro_sa)
cds_fibro_sa@clusters$UMAP$partitions <- as.factor(recreate.partition)

cds_fibro_sa <- learn_graph(
  cds_fibro_sa,
  use_partition = FALSE,
  close_loop = FALSE
)
```

```{r}
fibro_types <- c(
  "Adventitial fibroblasts",
  "Alveolar fibroblasts",
  "Myofibroblasts",
  "Peribronchial fibroblasts"
)

fibro_genes <- c(
  # Matrix
  "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "FBLN1",

  # Fibroblast identity
  "PDGFRA", "CD34",

  # Myofibroblast / contractile
  "ACTA2", "TAGLN", "MYH11",

  # Fibrotic activation
  "POSTN", "SERPINE1", "TGFB1",

  # Senescence
  "CDKN1A", "GLB1", "GDF15",

  # Signaling
  "IL6ST", "BMPR2", "MYC"
)

fibro_genes <- fibro_genes[fibro_genes %in% rownames(lungQuery)]

############################################################
# PART 1: Saccular vs Alveolar fibroblast analysis
############################################################

saccular_donors <- c("s088", "s062", "s229", "s232")

fibro_sa <- subset(
  lungQuery,
  subset =
    (
      Donor %in% saccular_donors |
      Donor_Group == "FT_NEWBORN"
    ) &
    predicted.ann_finest_level %in% fibro_types
)

fibro_sa$Stage <- ifelse(
  fibro_sa$Donor %in% saccular_donors,
  "Saccular",
  "Alveolar"
)

fibro_sa$Stage <- factor(
  fibro_sa$Stage,
  levels = c("Saccular", "Alveolar")
)

table(fibro_sa$Stage)
table(fibro_sa$predicted.ann_finest_level)

outdir_sa <- "Fibroblast_Output/Saccular_vs_Alveolar"
dir.create(outdir_sa, recursive = TRUE, showWarnings = FALSE)

############################################################
# UMAP: subtype
############################################################

p_fibro_umap_subtype <- DimPlot(
  fibro_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  label = TRUE
) +
  ggtitle("Fibroblast subtypes: Saccular and Alveolar")

p_fibro_umap_subtype

ggsave(
  file.path(outdir_sa, "01_Fibroblast_UMAP_by_Subtype.png"),
  p_fibro_umap_subtype,
  width = 8,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# UMAP: Stage
############################################################

p_fibro_umap_stage <- DimPlot(
  fibro_sa,
  reduction = "umap",
  group.by = "Stage"
) +
  ggtitle("Saccular versus Alveolar fibroblasts")

p_fibro_umap_stage

ggsave(
  file.path(outdir_sa, "02_Fibroblast_UMAP_by_Stage.png"),
  p_fibro_umap_stage,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# Split UMAP by stage
############################################################

p_fibro_umap_split <- DimPlot(
  fibro_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE
) +
  ggtitle("Fibroblast subtypes split by developmental stage")

p_fibro_umap_split

ggsave(
  file.path(outdir_sa, "03_Fibroblast_UMAP_Split_by_Stage.png"),
  p_fibro_umap_split,
  width = 12,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# DotPlot: Saccular vs Alveolar
############################################################

p_fibro_dot_sa <- DotPlot(
  fibro_sa,
  features = fibro_genes,
  group.by = "Stage"
) +
  RotatedAxis() +
  ggtitle("Fibroblast-associated genes in Saccular and Alveolar stages") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 10),
    plot.title = element_text(hjust = 0.5)
  )

p_fibro_dot_sa

ggsave(
  file.path(outdir_sa, "04_Fibroblast_DotPlot_Saccular_vs_Alveolar.png"),
  p_fibro_dot_sa,
  width = 10,
  height = 4,
  dpi = 300,
  bg = "white"
)

############################################################
# Heatmap: Saccular vs Alveolar
############################################################

avg_fibro_sa <- AverageExpression(
  fibro_sa,
  assays = "RNA",
  features = fibro_genes,
  group.by = "Stage"
)$RNA

avg_fibro_sa <- avg_fibro_sa[, c("Saccular", "Alveolar")]

avg_fibro_sa_scaled <- t(scale(t(avg_fibro_sa)))

avg_fibro_sa_scaled[avg_fibro_sa_scaled > 2] <- 2
avg_fibro_sa_scaled[avg_fibro_sa_scaled < -2] <- -2

write.csv(
  avg_fibro_sa_scaled,
  file.path(outdir_sa, "05_Fibroblast_Saccular_vs_Alveolar_Zscore_Matrix.csv"),
  quote = FALSE
)

pdf(
  file.path(outdir_sa, "05_Fibroblast_Heatmap_Saccular_vs_Alveolar.pdf"),
  width = 6,
  height = 7
)

pheatmap(
  avg_fibro_sa_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  fontsize_row = 10,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast gene expression: Saccular vs Alveolar"
)

dev.off()

pheatmap(
  avg_fibro_sa_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  fontsize_row = 10,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast gene expression: Saccular vs Alveolar"
)

############################################################
# Optional: Fibroblast pseudotime, Saccular vs Alveolar
############################################################

Idents(fibro_sa) <- "predicted.ann_finest_level"

cds_fibro_sa <- as.cell_data_set(fibro_sa)

rowData(cds_fibro_sa)$gene_name <- rownames(cds_fibro_sa)
rowData(cds_fibro_sa)$gene_short_name <- rownames(cds_fibro_sa)

cds_fibro_sa@int_colData@listData$reducedDims$UMAP <-
  fibro_sa@reductions$umap@cell.embeddings

cds_fibro_sa <- cluster_cells(
  cds_fibro_sa,
  reduction_method = "UMAP"
)

recreate.partition <- c(rep(1, ncol(cds_fibro_sa)))
names(recreate.partition) <- colnames(cds_fibro_sa)
cds_fibro_sa@clusters$UMAP$partitions <- as.factor(recreate.partition)

cds_fibro_sa <- learn_graph(
  cds_fibro_sa,
  use_partition = FALSE,
  close_loop = FALSE
)

get_root_fibro <- function(cds, root_cell_type = "Adventitial fibroblasts") {

  cell_ids <- colnames(cds)[
    colData(cds)$predicted.ann_finest_level == root_cell_type
  ]

  closest_vertex <-
    cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex

  closest_vertex <- as.matrix(closest_vertex)
  closest_vertex <- closest_vertex[colnames(cds), , drop = FALSE]

  root_vertex <- names(
    which.max(table(closest_vertex[cell_ids, 1]))
  )

  root_pr_node <- igraph::V(principal_graph(cds)[["UMAP"]])$name[
    as.numeric(root_vertex)
  ]

  return(root_pr_node)
}

root_fibro <- get_root_fibro(
  cds_fibro_sa,
  root_cell_type = "Adventitial fibroblasts"
)

cds_fibro_sa <- order_cells(
  cds_fibro_sa,
  reduction_method = "UMAP",
  root_pr_nodes = root_fibro
)

colData(cds_fibro_sa)$monocle3_pseudotime <- pseudotime(cds_fibro_sa)

p_fibro_pseudotime <- plot_cells(
  cds_fibro_sa,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Fibroblast pseudotime: Saccular vs Alveolar") +
  theme_classic(base_size = 14)

p_fibro_pseudotime

ggsave(
  file.path(outdir_sa, "06_Fibroblast_Pseudotime_UMAP.png"),
  p_fibro_pseudotime,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# PART 2: Fibroblast markers across developmental age groups
# Excluding PT_BPD and Aged_or_Diseased
############################################################

age_order <- c(
  "PT_NEWBORN",
  "FT_NEWBORN",
  "INFANT",
  "Children",
  "Adolescent",
  "Young_Adult"
)

fibro_age <- subset(
  lungQuery,
  subset =
    Donor_Group %in% age_order &
    predicted.ann_finest_level %in% fibro_types
)

fibro_age$Donor_Group <- factor(
  fibro_age$Donor_Group,
  levels = age_order
)

table(fibro_age$Donor_Group)
table(fibro_age$predicted.ann_finest_level)

outdir_age <- "Fibroblast_Output/Developmental_Age_Groups"
dir.create(outdir_age, recursive = TRUE, showWarnings = FALSE)

############################################################
# UMAP: age groups
############################################################

p_fibro_age_umap <- DimPlot(
  fibro_age,
  reduction = "umap",
  group.by = "Donor_Group"
) +
  ggtitle("Fibroblast populations across developmental age groups")

p_fibro_age_umap

ggsave(
  file.path(outdir_age, "01_Fibroblast_UMAP_by_Age_Group.png"),
  p_fibro_age_umap,
  width = 8,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# UMAP: fibroblast subtype
############################################################

p_fibro_age_subtype <- DimPlot(
  fibro_age,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  label = TRUE
) +
  ggtitle("Fibroblast subtypes across development")

p_fibro_age_subtype

ggsave(
  file.path(outdir_age, "02_Fibroblast_UMAP_by_Subtype_Age_Groups.png"),
  p_fibro_age_subtype,
  width = 8,
  height = 6,
  dpi = 300,
  bg = "white"
)

############################################################
# DotPlot across age groups
############################################################

p_fibro_dot_age <- DotPlot(
  fibro_age,
  features = fibro_genes,
  group.by = "Donor_Group"
) +
  RotatedAxis() +
  ggtitle("Fibroblast-associated genes across development") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    axis.text.y = element_text(size = 10),
    plot.title = element_text(hjust = 0.5)
  )

p_fibro_dot_age

ggsave(
  file.path(outdir_age, "03_Fibroblast_DotPlot_Age_Groups.png"),
  p_fibro_dot_age,
  width = 12,
  height = 5,
  dpi = 300,
  bg = "white"
)

############################################################
# Heatmap across age groups
############################################################

avg_fibro_age <- AverageExpression(
  fibro_age,
  assays = "RNA",
  features = fibro_genes,
  group.by = "Donor_Group"
)$RNA

avg_fibro_age <- avg_fibro_age[
  fibro_genes,
  age_order[age_order %in% colnames(avg_fibro_age)]
]

avg_fibro_age_scaled <- t(scale(t(avg_fibro_age)))

avg_fibro_age_scaled[avg_fibro_age_scaled > 2] <- 2
avg_fibro_age_scaled[avg_fibro_age_scaled < -2] <- -2

write.csv(
  avg_fibro_age_scaled,
  file.path(outdir_age, "04_Fibroblast_Age_Groups_Zscore_Matrix.csv"),
  quote = FALSE
)

pdf(
  file.path(outdir_age, "04_Fibroblast_Heatmap_Age_Groups.pdf"),
  width = 8,
  height = 7
)

pheatmap(
  avg_fibro_age_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  fontsize_row = 10,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast gene expression across development"
)

dev.off()

pheatmap(
  avg_fibro_age_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  fontsize_row = 10,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast gene expression across development"
)
```

```{r}
p_fibro_umap_subtype <- DimPlot(
  fibro_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  label = TRUE
)
print(p_fibro_umap_subtype)
```

```{r}
saccular_donors <- c("s088", "s062", "s229", "s232")

fibro_types <- c(
  "Adventitial fibroblasts",
  "Alveolar fibroblasts",
  "Myofibroblasts",
  "Peribronchial fibroblasts"
)

stroma_sa <- subset(
  lungQuery,
  subset =
    (
      Donor %in% saccular_donors |
      Donor_Group == "FT_NEWBORN"
    ) &
    predicted.ann_finest_level %in% fibro_types
)

stroma_sa$Stage <- ifelse(
  stroma_sa$Donor %in% saccular_donors,
  "Saccular",
  "Alveolar"
)

stroma_sa$Stage <- factor(
  stroma_sa$Stage,
  levels = c("Saccular", "Alveolar")
)

table(stroma_sa$Stage)
table(stroma_sa$predicted.ann_finest_level)
```

```{r}
p_stroma_umap <- DimPlot(
  stroma_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE
) +
  ggtitle("Fibroblast/stromal subtypes in saccular and alveolar stages")

p_stroma_umap
```

```{r}
cds_fibro_saccular <- cds_fibro_sa[
  ,
  colData(cds_fibro_sa)$Stage == "Saccular"
]

plot_cells(
  cds_fibro_saccular,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Saccular fibroblast pseudotime") +
  theme_classic(base_size = 14)
```

```{r}
cds_fibro_alveolar <- cds_fibro_sa[
  ,
  colData(cds_fibro_sa)$Stage == "Alveolar"
]

plot_cells(
  cds_fibro_alveolar,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Alveolar fibroblast pseudotime") +
  theme_classic(base_size = 14)
```

```{r}
plot_cells(
  cds_fibro_saccular,
  color_cells_by = "pseudotime"
)

plot_cells(
  cds_fibro_alveolar,
  color_cells_by = "pseudotime"
)
```

```{r}
root_fibro_saccular <- get_root_fibro(
  cds_fibro_saccular,
  root_cell_type = "Adventitial fibroblasts"
)

cds_fibro_saccular <- order_cells(
  cds_fibro_saccular,
  reduction_method = "UMAP",
  root_pr_nodes = root_fibro_saccular
)

colData(cds_fibro_saccular)$monocle3_pseudotime <- pseudotime(cds_fibro_saccular)
```

```{r}
p_saccular_fibro <- plot_cells(
  cds_fibro_saccular,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Saccular fibroblast pseudotime") +
  theme_classic(base_size = 14)

p_saccular_fibro
```

```{r}
fibro_alveolar <- subset(
  fibro_sa,
  subset = Stage == "Alveolar"
)

cds_fibro_alveolar <- as.cell_data_set(fibro_alveolar)

rowData(cds_fibro_alveolar)$gene_name <- rownames(cds_fibro_alveolar)
rowData(cds_fibro_alveolar)$gene_short_name <- rownames(cds_fibro_alveolar)

cds_fibro_alveolar@int_colData@listData$reducedDims$UMAP <-
  fibro_alveolar@reductions$umap@cell.embeddings

cds_fibro_alveolar <- cluster_cells(
  cds_fibro_alveolar,
  reduction_method = "UMAP"
)

cds_fibro_alveolar <- learn_graph(
  cds_fibro_alveolar,
  use_partition = FALSE,
  close_loop = FALSE
)

root_fibro_alveolar <- get_root_fibro(
  cds_fibro_alveolar,
  root_cell_type = "Adventitial fibroblasts"
)

cds_fibro_alveolar <- order_cells(
  cds_fibro_alveolar,
  reduction_method = "UMAP",
  root_pr_nodes = root_fibro_alveolar
)

colData(cds_fibro_alveolar)$monocle3_pseudotime <-
  pseudotime(cds_fibro_alveolar)

p_alveolar_fibro <- plot_cells(
  cds_fibro_alveolar,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Alveolar fibroblast pseudotime") +
  theme_classic(base_size = 14)

print(p_alveolar_fibro)
```

```{r}
sac_df <- as.data.frame(colData(cds_fibro_saccular)) %>%
  mutate(
    Stage = "Saccular",
    monocle3_pseudotime = pseudotime(cds_fibro_saccular)
  )

alv_df <- as.data.frame(colData(cds_fibro_alveolar)) %>%
  mutate(
    Stage = "Alveolar",
    monocle3_pseudotime = pseudotime(cds_fibro_alveolar)
  )

fibro_pseudo_compare <- bind_rows(sac_df, alv_df) %>%
  filter(is.finite(monocle3_pseudotime))

fibro_pseudo_compare$Stage <- factor(
  fibro_pseudo_compare$Stage,
  levels = c("Saccular", "Alveolar")
)

p_fibro_box_stage <- ggplot(
  fibro_pseudo_compare,
  aes(
    x = Stage,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(outlier.size = 0.3, alpha = 0.8) +
  geom_jitter(width = 0.15, size = 0.2, alpha = 0.2) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Fibroblast pseudotime distribution by developmental stage"
  ) +
  theme(legend.position = "none")

print(p_fibro_box_stage)
```

```{r}
p_fibro_box_subtype <- ggplot(
  fibro_pseudo_compare,
  aes(
    x = predicted.ann_finest_level,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    position = position_dodge(0.8),
    outlier.size = 0.3
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Pseudotime distribution across fibroblast states"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

print(p_fibro_box_subtype)
```

```{r}
stroma_genes_heatmap <- c(
  # Fibroblast identity / ECM
  "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "FBLN1",

  # Alveolar/adventitial fibroblast markers
  "PDGFRA", "CD34", "PI16", "APOD",

  # Myofibroblast / contractile
  "ACTA2", "TAGLN", "MYH11",

  # Fibrotic activation
  "POSTN", "SERPINE1", "TGFB1", "TGFB2",

  # Senescence
  "CDKN1A", "GLB1", "GDF15",

  # Inflammatory/signaling
  "IL6ST", "IL1B", "BMPR2", "MYC"
)

stroma_genes_heatmap <- stroma_genes_heatmap[
  stroma_genes_heatmap %in% rownames(cds_fibro_sa)
]
```

```{r}
pseudo_stroma <- pseudotime(cds_fibro_sa)

valid_stroma_cells <- names(pseudo_stroma)[
  is.finite(pseudo_stroma) & !is.na(pseudo_stroma)
]

valid_stroma_cells <- valid_stroma_cells[
  order(pseudo_stroma[valid_stroma_cells])
]

expr_stroma <- exprs(cds_fibro_sa)[
  stroma_genes_heatmap,
  valid_stroma_cells
]

expr_stroma <- as.matrix(expr_stroma)
```

```{r}
n_bins <- 50

bins_stroma <- cut(
  pseudo_stroma[valid_stroma_cells],
  breaks = n_bins,
  labels = FALSE
)

bin_expr_stroma <- sapply(
  sort(unique(bins_stroma)),
  function(b) {
    rowMeans(expr_stroma[, bins_stroma == b, drop = FALSE])
  }
)

colnames(bin_expr_stroma) <- paste0("Bin_", seq_len(ncol(bin_expr_stroma)))
```

```{r}
bin_expr_stroma_scaled <- t(scale(t(bin_expr_stroma)))

bin_expr_stroma_scaled[bin_expr_stroma_scaled > 2] <- 2
bin_expr_stroma_scaled[bin_expr_stroma_scaled < -2] <- -2
```

```{r}
stroma_gene_order <- c(
  "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "FBLN1",
  "PDGFRA", "CD34", "PI16", "APOD",
  "ACTA2", "TAGLN", "MYH11",
  "POSTN", "SERPINE1", "TGFB1", "TGFB2",
  "CDKN1A", "GLB1", "GDF15",
  "IL6ST", "IL1B", "BMPR2", "MYC"
)

stroma_gene_order <- stroma_gene_order[
  stroma_gene_order %in% rownames(bin_expr_stroma_scaled)
]

mat_stroma_ordered <- bin_expr_stroma_scaled[
  stroma_gene_order,
  ,
  drop = FALSE
]
```

```{r}
stroma_gene_group <- data.frame(
  Gene_Group = c(
    rep("ECM/fibroblast markers", 6),
    rep("Adventitial/alveolar markers", 4),
    rep("Myofibroblast markers", 3),
    rep("Fibrotic activation markers", 4),
    rep("Senescence markers", 3),
    rep("Inflammatory/signaling markers", 4)
  )
)

rownames(stroma_gene_group) <- rownames(mat_stroma_ordered)

stroma_gaps_row <- c(6, 10, 13, 17, 20)
```

```{r}
pheatmap(
  mat_stroma_ordered,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  annotation_row = stroma_gene_group,
  gaps_row = stroma_gaps_row,
  show_colnames = FALSE,
  fontsize_row = 10,
  border_color = NA,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast/stromal gene dynamics across pseudotime"
)
```

```{r}
write.csv(
  mat_stroma_ordered,
  "Stroma_Fibroblast_Pseudotime_Heatmap_Zscore_Matrix.csv",
  quote = FALSE
)

write.csv(
  stroma_gene_group,
  "Stroma_Fibroblast_Pseudotime_Gene_Groups.csv",
  quote = FALSE
)

pdf(
  "Stroma_Fibroblast_Pseudotime_Heatmap.pdf",
  width = 8,
  height = 9
)

pheatmap(
  mat_stroma_ordered,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  annotation_row = stroma_gene_group,
  gaps_row = stroma_gaps_row,
  show_colnames = FALSE,
  fontsize_row = 10,
  border_color = NA,
  breaks = seq(-2, 2, length.out = 100),
  main = "Fibroblast/stromal gene dynamics across pseudotime"
)

dev.off()
```

```{r}
sac_df <- as.data.frame(colData(cds_fibro_saccular))

sac_df$Stage <- "Saccular"
sac_df$monocle3_pseudotime <- pseudotime(cds_fibro_saccular)

alv_df <- as.data.frame(colData(cds_fibro_alveolar))

alv_df$Stage <- "Alveolar"
alv_df$monocle3_pseudotime <- pseudotime(cds_fibro_alveolar)

fibro_box_df <- bind_rows(
  sac_df,
  alv_df
)

fibro_box_df <- fibro_box_df[
  is.finite(fibro_box_df$monocle3_pseudotime),
]

fibro_box_df$Stage <- factor(
  fibro_box_df$Stage,
  levels = c("Saccular", "Alveolar")
)

p_fibro_stage <- ggplot(
  fibro_box_df,
  aes(
    x = Stage,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    outlier.size = 0.3,
    alpha = 0.8
  ) +
  geom_jitter(
    width = 0.15,
    size = 0.2,
    alpha = 0.2
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Fibroblast pseudotime distribution by developmental stage"
  ) +
  theme(
    legend.position = "none"
  )

p_fibro_stage
```

```{r}
p_fibro_subtype <- ggplot(
  fibro_box_df,
  aes(
    x = predicted.ann_finest_level,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    position = position_dodge(0.8),
    outlier.size = 0.2
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Pseudotime distribution across fibroblast states"
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

p_fibro_subtype
```

```{r}
ggsave(
  "Fibroblast_Pseudotime_Boxplot_Saccular_vs_Alveolar.png",
  p_fibro_stage,
  width = 5,
  height = 5,
  dpi = 300,
  bg = "white"
)

ggsave(
  "Fibroblast_Pseudotime_BySubtype_Saccular_vs_Alveolar.png",
  p_fibro_subtype,
  width = 8,
  height = 5,
  dpi = 300,
  bg = "white"
)
```


```{r}
stroma_types_use <- c(
  "Alveolar fibroblasts",
  "Adventitial fibroblasts",
  "Myofibroblasts",
  "Peribronchial fibroblasts",
  "Pericytes",
  "Smooth muscle",
  "SM activated stress response"
)
```

```{r}
saccular_donors <- c("s088", "s062", "s229", "s232")

stroma_types_use <- c(
  "Alveolar fibroblasts",
  "Adventitial fibroblasts",
  "Myofibroblasts",
  "Peribronchial fibroblasts",
  "Pericytes",
  "Smooth muscle",
  "SM activated stress response"
)

stroma_sa <- subset(
  lungQuery,
  subset =
    (
      Donor %in% saccular_donors |
      Donor_Group == "FT_NEWBORN"
    ) &
    predicted.ann_finest_level %in% stroma_types_use
)

stroma_sa$Stage <- ifelse(
  stroma_sa$Donor %in% saccular_donors,
  "Saccular",
  "Alveolar"
)

stroma_sa$Stage <- factor(
  stroma_sa$Stage,
  levels = c("Saccular", "Alveolar")
)

table(stroma_sa$Stage)
table(stroma_sa$predicted.ann_finest_level)
```

```{r}
stroma_markers <- c(
  # Fibroblast / ECM
  "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "FBLN1",

  # Fibroblast identity
  "PDGFRA", "PDGFRB", "CD34", "PI16",

  # Pericyte / smooth muscle
  "RGS5", "CSPG4", "MCAM", "ACTA2", "TAGLN", "MYH11",

  # Activation / fibrosis
  "POSTN", "SERPINE1", "TGFB1", "TGFB2",

  # Senescence / inflammatory / repair
  "CDKN1A", "GLB1", "GDF15", "IL6ST", "IL1B", "BMPR2", "MYC"
)

stroma_markers <- stroma_markers[
  stroma_markers %in% rownames(stroma_sa)
]
```

```{r}
p_umap_subtype <- DimPlot(
  stroma_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  label = TRUE,
  repel = TRUE
) +
  ggtitle("Stromal subtypes in saccular and alveolar stages")

p_umap_subtype
```

```{r}
p_umap_split <- DimPlot(
  stroma_sa,
  reduction = "umap",
  group.by = "predicted.ann_finest_level",
  split.by = "Stage",
  label = TRUE,
  repel = TRUE
) +
  ggtitle("Stromal subtypes split by developmental stage")

p_umap_split
```

```{r}
avg_stroma <- AverageExpression(
  stroma_sa,
  assays = "RNA",
  features = stroma_markers,
  group.by = "Stage"
)$RNA

avg_stroma <- avg_stroma[, c("Saccular", "Alveolar")]

avg_stroma_scaled <- t(scale(t(avg_stroma)))

avg_stroma_scaled[avg_stroma_scaled > 2] <- 2
avg_stroma_scaled[avg_stroma_scaled < -2] <- -2

pheatmap(
  avg_stroma_scaled,
  cluster_rows = TRUE,
  cluster_cols = FALSE,
  fontsize_row = 9,
  breaks = seq(-2, 2, length.out = 100),
  main = "Stromal marker expression: Saccular vs Alveolar"
)
```

```{r}
senescence_genes <- c(
  "CDKN1A", "GLB1", "GDF15", "SERPINE1", "IL6ST"
)

plasticity_genes <- c(
  "MYC", "TGFB1", "TGFB2", "BMPR2", "PDGFRA", "PDGFRB"
)

ecm_genes <- c(
  "COL1A1", "COL1A2", "COL3A1", "DCN", "LUM", "FBLN1", "POSTN"
)

senescence_genes <- senescence_genes[senescence_genes %in% rownames(stroma_sa)]
plasticity_genes <- plasticity_genes[plasticity_genes %in% rownames(stroma_sa)]
ecm_genes <- ecm_genes[ecm_genes %in% rownames(stroma_sa)]

stroma_sa <- AddModuleScore(
  stroma_sa,
  features = list(senescence_genes),
  name = "SenescenceScore"
)

stroma_sa <- AddModuleScore(
  stroma_sa,
  features = list(plasticity_genes),
  name = "PlasticityScore"
)

stroma_sa <- AddModuleScore(
  stroma_sa,
  features = list(ecm_genes),
  name = "ECMScore"
)
```

```{r}
p_box_sen <- ggplot(
  stroma_sa@meta.data,
  aes(
    x = Stage,
    y = SenescenceScore1,
    fill = Stage
  )
) +
  geom_boxplot(outlier.size = 0.3, alpha = 0.8) +
  geom_jitter(width = 0.15, size = 0.2, alpha = 0.15) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Senescence module score",
    title = "Stromal senescence score"
  ) +
  theme(legend.position = "none")

p_box_sen
```

```{r}
p_box_plasticity <- ggplot(
  stroma_sa@meta.data,
  aes(
    x = Stage,
    y = PlasticityScore1,
    fill = Stage
  )
) +
  geom_boxplot(outlier.size = 0.3, alpha = 0.8) +
  geom_jitter(width = 0.15, size = 0.2, alpha = 0.15) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Plasticity module score",
    title = "Stromal plasticity score"
  ) +
  theme(legend.position = "none")

p_box_plasticity
```

```{r}
p_box_ecm <- ggplot(
  stroma_sa@meta.data,
  aes(
    x = Stage,
    y = ECMScore1,
    fill = Stage
  )
) +
  geom_boxplot(outlier.size = 0.3, alpha = 0.8) +
  geom_jitter(width = 0.15, size = 0.2, alpha = 0.15) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "ECM module score",
    title = "Stromal ECM score"
  ) +
  theme(legend.position = "none")

p_box_ecm
```

```{r}
write.csv(
  avg_stroma_scaled,
  "Stroma_Saccular_vs_Alveolar_Heatmap_Zscore_Matrix.csv",
  quote = FALSE
)

write.csv(
  stroma_sa@meta.data,
  "Stroma_Saccular_vs_Alveolar_Metadata_With_ModuleScores.csv",
  row.names = TRUE
)
```

```{r}
fibro_pseudo_df <- as.data.frame(colData(cds_fibro_sa)) %>%
  filter(is.finite(monocle3_pseudotime))

fibro_pseudo_df$Stage <- factor(
  fibro_pseudo_df$Stage,
  levels = c("Saccular", "Alveolar")
)

fibro_pseudo_df$predicted.ann_finest_level <- factor(
  fibro_pseudo_df$predicted.ann_finest_level,
  levels = c(
    "Adventitial fibroblasts",
    "Alveolar fibroblasts",
    "Peribronchial fibroblasts",
    "Myofibroblasts",
    "Pericytes",
    "Smooth muscle",
    "SM activated stress response"
  )
)

p_fibro_box <- ggplot(
  fibro_pseudo_df,
  aes(
    x = predicted.ann_finest_level,
    y = monocle3_pseudotime,
    fill = Stage
  )
) +
  geom_boxplot(
    position = position_dodge(0.8),
    outlier.size = 0.25,
    alpha = 0.85
  ) +
  theme_classic(base_size = 14) +
  labs(
    x = "",
    y = "Monocle3 pseudotime",
    title = "Pseudotime distribution across stromal states"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 12)
  )

p_fibro_box
```

```{r}
ggsave(
  "Stromal_Pseudotime_Distribution_Across_States.png",
  p_fibro_box,
  width = 9,
  height = 5,
  dpi = 300,
  bg = "white"
)
```

```{r}
library(igraph)

get_root_stroma <- function(
  cds,
  root_cell_type = "Adventitial fibroblasts"
) {

  cell_ids <- colnames(cds)[
    colData(cds)$predicted.ann_finest_level == root_cell_type
  ]

  closest_vertex <-
    cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex

  closest_vertex <- as.matrix(closest_vertex)

  closest_vertex <- closest_vertex[
    colnames(cds),
    ,
    drop = FALSE
  ]

  root_vertex <- names(
    which.max(
      table(
        closest_vertex[cell_ids, 1]
      )
    )
  )

  root_pr_node <- igraph::V(
    principal_graph(cds)[["UMAP"]]
  )$name[
    as.numeric(root_vertex)
  ]

  return(root_pr_node)
}
```

```{r}
root_saccular <- get_root_stroma(
  cds_stroma_saccular,
  root_cell_type = "Adventitial fibroblasts"
)
```


```{r}
stroma_saccular <- subset(
  stroma_sa,
  subset = Stage == "Saccular"
)

Idents(stroma_saccular) <- "predicted.ann_finest_level"

cds_stroma_saccular <- as.cell_data_set(stroma_saccular)

rowData(cds_stroma_saccular)$gene_name <- rownames(cds_stroma_saccular)
rowData(cds_stroma_saccular)$gene_short_name <- rownames(cds_stroma_saccular)

cds_stroma_saccular@int_colData@listData$reducedDims$UMAP <-
  stroma_saccular@reductions$umap@cell.embeddings

cds_stroma_saccular <- cluster_cells(
  cds_stroma_saccular,
  reduction_method = "UMAP"
)

cds_stroma_saccular <- learn_graph(
  cds_stroma_saccular,
  use_partition = FALSE,
  close_loop = FALSE
)

root_saccular <- get_root_stroma(
  cds_stroma_saccular,
  root_cell_type = "Adventitial fibroblasts"
)

cds_stroma_saccular <- order_cells(
  cds_stroma_saccular,
  reduction_method = "UMAP",
  root_pr_nodes = root_saccular
)

colData(cds_stroma_saccular)$monocle3_pseudotime <-
  pseudotime(cds_stroma_saccular)

p_stroma_saccular <- plot_cells(
  cds_stroma_saccular,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Saccular stromal pseudotime") +
  theme_classic(base_size = 14)

print(p_stroma_saccular)
```

```{r}
stroma_alveolar <- subset(
  stroma_sa,
  subset = Stage == "Alveolar"
)

Idents(stroma_alveolar) <- "predicted.ann_finest_level"

cds_stroma_alveolar <- as.cell_data_set(stroma_alveolar)

rowData(cds_stroma_alveolar)$gene_name <- rownames(cds_stroma_alveolar)
rowData(cds_stroma_alveolar)$gene_short_name <- rownames(cds_stroma_alveolar)

cds_stroma_alveolar@int_colData@listData$reducedDims$UMAP <-
  stroma_alveolar@reductions$umap@cell.embeddings

cds_stroma_alveolar <- cluster_cells(
  cds_stroma_alveolar,
  reduction_method = "UMAP"
)

cds_stroma_alveolar <- learn_graph(
  cds_stroma_alveolar,
  use_partition = FALSE,
  close_loop = FALSE
)

root_alveolar <- get_root_stroma(
  cds_stroma_alveolar,
  root_cell_type = "Adventitial fibroblasts"
)

cds_stroma_alveolar <- order_cells(
  cds_stroma_alveolar,
  reduction_method = "UMAP",
  root_pr_nodes = root_alveolar
)

colData(cds_stroma_alveolar)$monocle3_pseudotime <-
  pseudotime(cds_stroma_alveolar)

p_stroma_alveolar <- plot_cells(
  cds_stroma_alveolar,
  color_cells_by = "pseudotime",
  label_cell_groups = FALSE,
  label_groups_by_cluster = FALSE,
  label_leaves = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE
) +
  ggtitle("Alveolar stromal pseudotime") +
  theme_classic(base_size = 14)

print(p_stroma_alveolar)
```

```{r}
ggsave(
  "Saccular_Stromal_Pseudotime.png",
  p_stroma_saccular,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)

ggsave(
  "Alveolar_Stromal_Pseudotime.png",
  p_stroma_alveolar,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)
```

```{r}
dir.create(
  "Stromal_Pseudotime_Output",
  showWarnings = FALSE
)

ggsave(
  "Stromal_Pseudotime_Output/Saccular_Stromal_Pseudotime.png",
  p_stroma_saccular,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)

ggsave(
  "Stromal_Pseudotime_Output/Alveolar_Stromal_Pseudotime.png",
  p_stroma_alveolar,
  width = 7,
  height = 6,
  dpi = 300,
  bg = "white"
)
```

```{r}
write.csv(
  as.data.frame(colData(cds_stroma_saccular)),
  "Stromal_Pseudotime_Output/Saccular_Pseudotime_Metadata.csv"
)

write.csv(
  as.data.frame(colData(cds_stroma_alveolar)),
  "Stromal_Pseudotime_Output/Alveolar_Pseudotime_Metadata.csv"
)
```

```{r}
library(Seurat)
library(dplyr)
library(pheatmap)

my_colors <- colorRampPalette(
  c("#2166AC", "#F7F7F7", "#FDB863")
)(100)

gene_order <- c(
  "COL1A1","COL1A2","COL3A1","DCN","LUM","FBLN1",
  "PDGFRA","CD34","PI16","APOD",
  "ACTA2","TAGLN","MYH11",
  "POSTN","SERPINE1","TGFB1","TGFB2",
  "ARNTL","CLOCK","NR1D1","PER1","PER2","DBP",
  "CDKN1A","GLB1","GDF15",
  "IL6ST","IL1B","BMPR2","MYC"
)

gene_order <- gene_order[gene_order %in% rownames(obj_stage)]

avg_stage <- AverageExpression(
  obj_stage,
  features = gene_order,
  group.by = "Clock_Stage",
  assays = "RNA",
  layer = "data"
)$RNA

avg_stage <- as.matrix(avg_stage)

avg_stage <- avg_stage[
  gene_order,
  c("Saccular", "Alveolar", "PT_BPD"),
  drop = FALSE
]

avg_stage_z <- t(scale(t(avg_stage)))
avg_stage_z[!is.finite(avg_stage_z)] <- 0

gene_group <- c(
  rep("ECM/fibroblast markers", 6),
  rep("Adventitial/alveolar markers", 4),
  rep("Myofibroblast markers", 3),
  rep("Fibrotic activation markers", 4),
  rep("Clock markers", 6),
  rep("Senescence markers", 3),
  rep("Inflammatory/signaling markers", 4)
)

names(gene_group) <- c(
  "COL1A1","COL1A2","COL3A1","DCN","LUM","FBLN1",
  "PDGFRA","CD34","PI16","APOD",
  "ACTA2","TAGLN","MYH11",
  "POSTN","SERPINE1","TGFB1","TGFB2",
  "ARNTL","CLOCK","NR1D1","PER1","PER2","DBP",
  "CDKN1A","GLB1","GDF15",
  "IL6ST","IL1B","BMPR2","MYC"
)

annotation_row <- data.frame(
  Gene_Group = gene_group[rownames(avg_stage_z)]
)

rownames(annotation_row) <- rownames(avg_stage_z)

ann_colors <- list(
  Gene_Group = c(
    "ECM/fibroblast markers" = "#E78BE7",
    "Adventitial/alveolar markers" = "#F4A6A6",
    "Myofibroblast markers" = "#28C9C9",
    "Fibrotic activation markers" = "#7AA6FF",
    "Clock markers" = "#7B68EE",
    "Senescence markers" = "#D4B000",
    "Inflammatory/signaling markers" = "#00C853"
  )
)

pheatmap(
  avg_stage_z,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  color = my_colors,
  annotation_row = annotation_row,
  annotation_colors = ann_colors,
  border_color = NA,
  fontsize_row = 11,
  fontsize_col = 13,
  main = "Stromal Gene Dynamics Across Developmental Stage"
)
```

